version: '3'
services:
  db-container:
    image: mysql:8.0
    platform: linux/amd64
    restart: always
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
     - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 15s
      timeout: 5s
      retries: 5

  phpmyadmin:
    depends_on:
      - db-container
    image: phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_HOST=db-container

  my-app:
    depends_on:
      db-container:
        condition: service_healthy
    image: 144.126.218.34:8083/my-app-docker-nexus:5.0
    environment:
     - DB_USER=${MYSQL_USER}
     - DB_PWD=${MYSQL_PASSWORD}
     - DB_SERVER=${DB_SERVER}
     - DB_NAME=${MYSQL_DATABASE}
    ports:
      - "8080:8080"
volumes:
  mysql-data:
    driver: local
